import { CollectibleTypeCustom } from "../enums/CollectibleTypeCustom";

export const TRANSFORMATION_HELPERS_SET: ReadonlySet<CollectibleTypeCustom> =
  new Set([
    CollectibleTypeCustom.COLLECTIBLE_GUPPY_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_BEELZEBUB_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_FUN_GUY_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_SERAPHIM_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_BOB_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_SPUN_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_YES_MOTHER_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_CONJOINED_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_LEVIATHAN_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_OH_CRAP_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_BOOKWORM_TRANSFORMATION_HELPER,
    CollectibleTypeCustom.COLLECTIBLE_SPIDER_BABY_TRANSFORMATION_HELPER,
  ]);
