import { Keyboard } from "isaac-typescript-definitions";

export const KEYBOARD_MAP: ReadonlyMap<
  Keyboard,
  [lowercase: string, uppercase: string]
> = new Map([
  [Keyboard.ZERO, ["0", ")"]],
  [Keyboard.ONE, ["1", "!"]],
  [Keyboard.TWO, ["2", "@"]],
  [Keyboard.THREE, ["3", "#"]],
  [Keyboard.FOUR, ["4", "$"]],
  [Keyboard.FIVE, ["5", "%"]],
  [Keyboard.SIX, ["6", "^"]],
  [Keyboard.SEVEN, ["7", "&"]],
  [Keyboard.EIGHT, ["8", "*"]],
  [Keyboard.NINE, ["9", "("]],
  [Keyboard.A, ["a", "A"]],
  [Keyboard.APOSTROPHE, ["'", '"']],
  [Keyboard.B, ["b", "B"]],
  [Keyboard.BACKSLASH, ["\\", "|"]],
  [Keyboard.C, ["c", "C"]],
  [Keyboard.COMMA, [",", "<"]],
  [Keyboard.D, ["d", "D"]],
  [Keyboard.E, ["e", "E"]],
  [Keyboard.EQUAL, ["=", "+"]],
  [Keyboard.F, ["f", "F"]],
  [Keyboard.G, ["g", "G"]],
  [Keyboard.GRAVE_ACCENT, ["`", "~"]],
  [Keyboard.H, ["h", "H"]],
  [Keyboard.I, ["i", "I"]],
  [Keyboard.J, ["j", "J"]],
  [Keyboard.K, ["k", "K"]],
  [Keyboard.KP_0, ["0", "0"]],
  [Keyboard.KP_1, ["1", "1"]],
  [Keyboard.KP_2, ["2", "2"]],
  [Keyboard.KP_3, ["3", "3"]],
  [Keyboard.KP_4, ["4", "4"]],
  [Keyboard.KP_5, ["5", "5"]],
  [Keyboard.KP_6, ["6", "6"]],
  [Keyboard.KP_7, ["7", "7"]],
  [Keyboard.KP_8, ["8", "8"]],
  [Keyboard.KP_9, ["9", "9"]],
  [Keyboard.KP_ADD, ["+", "+"]],
  [Keyboard.KP_DECIMAL, [".", "."]],
  [Keyboard.KP_DIVIDE, ["/", "/"]],
  [Keyboard.KP_MULTIPLY, ["*", "*"]],
  [Keyboard.KP_SUBTRACT, ["-", "-"]],
  [Keyboard.L, ["l", "L"]],
  [Keyboard.LEFT_BRACKET, ["[", "{"]],
  [Keyboard.M, ["m", "M"]],
  [Keyboard.MINUS, ["-", "_"]],
  [Keyboard.N, ["n", "N"]],
  [Keyboard.O, ["o", "O"]],
  [Keyboard.P, ["p", "P"]],
  [Keyboard.PERIOD, [".", ">"]],
  [Keyboard.Q, ["q", "Q"]],
  [Keyboard.R, ["r", "R"]],
  [Keyboard.RIGHT_BRACKET, ["]", "}"]],
  [Keyboard.S, ["s", "S"]],
  [Keyboard.SEMICOLON, [";", ":"]],
  [Keyboard.SLASH, ["/", "?"]],
  [Keyboard.SPACE, [" ", " "]],
  [Keyboard.T, ["t", "T"]],
  [Keyboard.U, ["u", "U"]],
  [Keyboard.V, ["v", "V"]],
  [Keyboard.W, ["w", "W"]],
  [Keyboard.X, ["x", "X"]],
  [Keyboard.Y, ["y", "Y"]],
  [Keyboard.Z, ["z", "Z"]],
]);
